regipy/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('regipys.urls', namespace='regipys')),
    url(r'^users/', include('users.urls', namespace='users')),

]

regipys/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [ # Home page
        url(r'^$', views.index, name='index'),
        ]

users/urls.py
"""Defines URL patterns for users"""
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
# Login page
url(r'^login/$', login, {'template_name': 'users/login.html'},
name='login'),
# Logout page
url(r'^logout/$', views.logout_view, name='logout'),
]

regipys/models.py
from django.db import models

# Create your models here.

class Year(models.Model):
    year_one = "year_one"
    year_two = "year_two"
    year_three = "year_three"
    year_four = "year_four"
    year_group_choices = (
        (year_one, "year_one"),
        (year_two, "year_two"),
        (year_three, "year_three"),
        (year_four, "year_four"),
    )
    year_group = models.CharField(max_length = 30, choices = year_group_choices, default = year_one)

    class Meta:
        verbose_name_plural = "Years"

class Child(models.Model):
    """Class relating to Children"""
    year_group = models.ForeignKey(Year, on_delete = models.CASCADE)
    first_name = models.CharField(max_length = 255)
    last_name = models.CharField(max_length = 255)

    class Meta:
        verbose_name_plural = "Children"
        
    def __str__(self):
        return self.text

users/models.py
from django.db import models

# Create your models here.

regipys/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'regipys/index.html')

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

regipys/templates/regipys/base.html
{% load bootstrap3 %} {% load bootstrap_themes %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
  <title>{% block title %}{%endblock title %} - RegiPy</title>
  {% bootstrap_javascript %}
  <link rel="stylesheet" type="text/css" href="https://bootswatch.com/paper/bootstrap.min.css">
  {% block style %} {% endblock style %}
</head>

<body>
  <div class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">RegiPy</a>
            <ul class="nav navbar-nav">
              {% if user.is_authenticated %}
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Student <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#"><span class="glyphicon glyphicon-plus"></span> Add Student</a></li>
                  <li class="divider"></li>
                  <li><a href="#"><span class="glyphicon glyphicon-search"></span> Student Search</a></li>
                </ul>
                </li>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Class <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#"><span class="glyphicon glyphicon-plus"></span> Add Class</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><span class="glyphicon glyphicon-search"></span> Class Search</a></li>
                  </ul>
                </li>
              {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <li><a href="{% url 'users:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Log Out {{ user.username }}</a></li>
              {% else %}
              <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <div class="page-header" style="margin-top:10%">
        <h4>{% block header %}{% endblock header %}<h4>
      </div>
  </div>
  <div class="container" id="block" style="width:100%">
    {% block content %}{% endblock content %}
  </div>
</div>
</body>

</html>

regipys/templates/regipys/index.html
{% extends "regipys/base.html" %}

{% load bootstrap3 %}

{% block title%}
Home Page
{% endblock title %}

{% block content %}
<div class="jumbotron jumbotron-fluid" style="width:50%; margin:0 auto; text-align:center">
  <h2>Welcome To RegiPy</h2>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends "regipys/base.html" %}
{% load bootstrap3 %}
{% block title %} Log in  {%endblock title %}
{% block header %}
Log in to your account
{% endblock header %}

{% block content %}
<div class="jumbotron" style="width: 50%; margin:0 auto;">
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Log In</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="#"/>
</form>
</div>
{% endblock content %}